# Generated by Django 4.1.5 on 2023-01-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pinned',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='Forum.organization'),
        ),
    ]
