# Generated by Django 4.1.5 on 2023-01-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_alter_profile_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pinned',
            field=models.ManyToManyField(blank=True, related_name='followers', to='Forum.organization'),
        ),
    ]
