# Generated by Django 4.1.5 on 2023-01-05 18:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_alter_profile_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='default.png', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Forum.profile'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Forum.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 1, 5), 'valid values are not in the past')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_project',
            field=models.BooleanField(default=False, verbose_name='Make this a project'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='is_icon',
            field=models.BooleanField(default=False, verbose_name='Make icon of post/project'),
        ),
    ]
