# Generated by Django 4.1.5 on 2023-01-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_alter_bid_bidder_alter_bid_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_project',
            field=models.BooleanField(default=False, verbose_name='Make this a project'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='is_icon',
            field=models.BooleanField(default=False, verbose_name='Make icon of post/project'),
        ),
    ]
