# Generated by Django 4.1.5 on 2023-01-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_postimage_image_alter_bid_bidder_alter_bid_event_and_more'),
        ('Forum', '0011_alter_postimage_image'),
    ]

    operations = [
    ]
