# Generated by Django 4.1.5 on 2023-01-10 13:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0013_organization_official_email_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('DN', 'Denied'), ('CP', 'Passed')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 1, 10), 'valid values are not in the past')]),
        ),
    ]
