# Generated by Django 4.1.5 on 2023-01-11 18:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0014_alter_bid_status_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 1, 11), 'valid values are not in the past')]),
        ),
    ]
